-- SmartTrack demo seed: 80 products, 80 stock batches, 40 batch updates, 80 transactions.
-- Requires MySQL 8.0+ for recursive CTEs.
-- Product stock distribution: 65 good, 10 moderate, 3 low, 2 critical.

START TRANSACTION;

-- Add 80 products with stable IDs P101-P180.
INSERT IGNORE INTO products
  (id, name, category, supplier, reorder, price, sale_price,
   unit_label, units_per_pack, pack_price, is_vat_exempt, status)
WITH RECURSIVE seq(n) AS (
  SELECT 1
  UNION ALL
  SELECT n + 1 FROM seq WHERE n < 80
)
SELECT
  CONCAT('P', LPAD(n + 100, 3, '0')),
  CONCAT(
    CASE MOD(n - 1, 9)
      WHEN 0 THEN 'Amoxicillin'
      WHEN 1 THEN 'Paracetamol'
      WHEN 2 THEN 'Metformin'
      WHEN 3 THEN 'Amlodipine'
      WHEN 4 THEN 'Cetirizine'
      WHEN 5 THEN 'Omeprazole'
      WHEN 6 THEN 'Ibuprofen'
      WHEN 7 THEN 'Salbutamol'
      ELSE 'Vitamin C'
    END,
    ' ', 50 + MOD(n * 25, 450),
    CASE WHEN MOD(n - 1, 9) = 7 THEN 'mcg' ELSE 'mg' END
  ),
  CASE MOD(n - 1, 9)
    WHEN 0 THEN 'Antibiotic'
    WHEN 1 THEN 'Analgesic'
    WHEN 2 THEN 'Antidiabetic'
    WHEN 3 THEN 'Antihypertensive'
    WHEN 4 THEN 'Antihistamine'
    WHEN 5 THEN 'Antacid'
    WHEN 6 THEN 'NSAID'
    WHEN 7 THEN 'Bronchodilator'
    ELSE 'Supplement'
  END,
  CONCAT('Demo Supplier ', LPAD(MOD(n - 1, 8) + 1, 2, '0')),
  CASE
    WHEN n <= 65 THEN 30
    WHEN n <= 75 THEN 50
    WHEN n <= 78 THEN 20
    ELSE 10
  END,
  ROUND(2.50 + MOD(n * 37, 1800) / 100, 2),
  NULL,
  CASE WHEN MOD(n - 1, 9) IN (0, 1, 2, 3) THEN 'tablet' ELSE 'unit' END,
  CASE WHEN MOD(n - 1, 9) = 8 THEN 20 ELSE 1 END,
  NULL,
  CASE WHEN MOD(n - 1, 9) IN (1, 2, 3) THEN 1 ELSE 0 END,
  CASE
    WHEN n <= 65 THEN 'good'
    WHEN n <= 75 THEN 'moderate'
    WHEN n <= 78 THEN 'low'
    ELSE 'critical'
  END
FROM seq;

-- Give every product one batch so no product is empty. Quantities intentionally
-- favor healthy stock and mirror each product's status.
INSERT IGNORE INTO product_batches
  (batch_id, product_id, qty, expiry_date, received_date, batch_total_cost, unit_cost)
WITH RECURSIVE seq(n) AS (
  SELECT 1
  UNION ALL
  SELECT n + 1 FROM seq WHERE n < 80
)
SELECT
  CONCAT('SEED-B', LPAD(n, 3, '0')),
  CONCAT('P', LPAD(n + 100, 3, '0')),
  CASE
    WHEN n <= 65 THEN 180 + MOD(n * 17, 220)
    WHEN n <= 75 THEN 65 + MOD(n * 5, 35)
    WHEN n <= 78 THEN 8 + MOD(n, 8)
    ELSE 2 + MOD(n, 3)
  END,
  DATE_ADD('2028-01-31', INTERVAL MOD(n * 11, 24) MONTH),
  DATE_SUB('2026-09-28', INTERVAL MOD(n * 3, 90) DAY),
  ROUND((2.50 + MOD(n * 29, 900) / 100) *
    CASE
      WHEN n <= 65 THEN 180 + MOD(n * 17, 220)
      WHEN n <= 75 THEN 65 + MOD(n * 5, 35)
      WHEN n <= 78 THEN 8 + MOD(n, 8)
      ELSE 2 + MOD(n, 3)
    END, 2),
  ROUND(2.50 + MOD(n * 29, 900) / 100, 4)
FROM seq;

-- Mark 40 batches as updated after receipt.
UPDATE product_batches
SET
  qty = qty + 10,
  batch_total_cost = ROUND((qty + 10) * unit_cost, 2),
  received_date = '2026-09-28'
WHERE batch_id LIKE 'SEED-B%'
  AND CAST(REPLACE(batch_id, 'SEED-B', '') AS UNSIGNED) BETWEEN 1 AND 40;

-- Add one completed sale transaction for each seeded product.
INSERT IGNORE INTO transactions
  (id, type, sale_group_id, product_name, product_id, qty, sale_qty,
   sale_unit, units_per_sale, amount, pre_tax_amount, tax_amount, tax_rate,
   staff, staff_id, status, note, transacted_at)
WITH RECURSIVE seq(n) AS (
  SELECT 1
  UNION ALL
  SELECT n + 1 FROM seq WHERE n < 80
)
SELECT
  CONCAT('SEEDTX', LPAD(n, 3, '0')),
  'sale',
  CONCAT('SEEDTX', LPAD(n, 3, '0')),
  p.name,
  p.id,
  1 + MOD(n, 3),
  1 + MOD(n, 3),
  'unit',
  1,
  ROUND(p.price * (1 + MOD(n, 3)), 2),
  CASE
    WHEN p.is_vat_exempt = 1 THEN ROUND(p.price * (1 + MOD(n, 3)), 2)
    ELSE ROUND((p.price * (1 + MOD(n, 3))) / 1.12, 2)
  END,
  CASE
    WHEN p.is_vat_exempt = 1 THEN 0.00
    ELSE ROUND((p.price * (1 + MOD(n, 3))) -
      ((p.price * (1 + MOD(n, 3))) / 1.12), 2)
  END,
  CASE WHEN p.is_vat_exempt = 1 THEN 0.0000 ELSE 0.1200 END,
  'Juan Dela Cruz',
  'U003',
  'completed',
  'Demo transaction generated by 80-product seed',
  DATE_SUB('2026-09-28 12:00:00', INTERVAL n DAY)
FROM seq
JOIN products p ON p.id = CONCAT('P', LPAD(n + 100, 3, '0'));

COMMIT;

-- Verification summary.
SELECT 'Seeded products' AS metric, COUNT(*) AS total
FROM products WHERE id BETWEEN 'P101' AND 'P180'
UNION ALL
SELECT 'Seeded batches', COUNT(*)
FROM product_batches WHERE batch_id LIKE 'SEED-B%'
UNION ALL
SELECT 'Updated batches', COUNT(*)
FROM product_batches
WHERE batch_id LIKE 'SEED-B%'
  AND CAST(REPLACE(batch_id, 'SEED-B', '') AS UNSIGNED) BETWEEN 1 AND 40
UNION ALL
SELECT 'Seeded transactions', COUNT(*)
FROM transactions WHERE id LIKE 'SEEDTX%';

SELECT status, COUNT(*) AS products
FROM products
WHERE id BETWEEN 'P101' AND 'P180'
GROUP BY status
ORDER BY FIELD(status, 'good', 'moderate', 'low', 'critical');